name: Deploy ChatKaro via MERN Platform

on:
  workflow_dispatch:
    inputs:
      target_cloud:
        required: true
      deployment_id:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # ===================================================================
    #  THE FIRST FIX IS HERE: Set a default working directory for all steps
    #  IMPORTANT: Change 'chatkaro' to the actual name of the subdirectory
    #  in your repository that contains package.json.
    # ===================================================================
    defaults:
      run:
        working-directory: ./chatkaro

    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4

      - name: 2. Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # These commands will now run inside the './chatkaro' directory
      - name: 3. Install Dependencies
        run: npm install

      - name: 4. Build Project
        run: npm run build

      - name: 5. Install Vercel CLI
        # Install CLI in the root, as it doesn't need to be in the subfolder
        run: npm install --global vercel
        working-directory: /home/runner/work/ChatKaro/ChatKaro # Override to run in root

      - name: 6. Deploy to Vercel
        id: deploy_step
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          # The path to the build output is now relative to the subfolder
          DEPLOYMENT_URL=$(vercel deploy ./build --prod --yes --token=${{ secrets.VERCEL_TOKEN }})
          echo "DEPLOYMENT_URL=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
      
      - name: 7. Report Success to API
        if: success()
        working-directory: /home/runner/work/ChatKaro/ChatKaro # Override to run in root
        run: |
          curl --fail -v -X PATCH '${{ secrets.API_URL }}/api/projects/${{ secrets.PROJECT_ID }}/deployments/${{ github.event.inputs.deployment_id }}' \
          -H "Content-Type: application/json" \
          --data-raw '{
            "status": "success",
            "deploymentUrl": "${{ steps.deploy_step.outputs.DEPLOYMENT_URL }}",
            "apiKey": "${{ secrets.ACTIONS_API_KEY }}"
          }'

      - name: 8. Report Failure to API
        if: failure()
        working-directory: /home/runner/work/ChatKaro/ChatKaro # Override to run in root
        run: |
          curl --fail -v -X PATCH '${{ secrets.API_URL }}/api/projects/${{ secrets.PROJECT_ID }}/deployments/${{ github.event.inputs.deployment_id }}' \
          -H "Content-Type: application/json" \
          --data-raw '{
            "status": "failure",
            "apiKey": "${{ secrets.ACTIONS_API_KEY }}"
          }'
