name: MERN Platform Deployment Trigger

on:
  workflow_dispatch" >> $GITHUB_OUTPUT

      - name: 4. Report Success to API
        if: success():
    inputs:
      target_cloud:
        required: true
      deployment_id:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

        run: |
          curl --fail -v -X PATCH '${{ secrets.API_URL }}/api/projects/${{ secrets.PROJECT_ID }}/deployments/${{ github.event.inputs.deployment_id      - name: 1. Checkout repository code
        uses: actions/checkout@v4

      - name:  }}' \
          -H "Content-Type: application/json" \
          --data-raw '{
            "status": "success",
            "deploymentUrl": "${{ steps.deploy_step.outputs.DEPLOYMENT_2. Install Vercel CLI
        run: npm install --global vercel

      - name: 3. DeployURL }}",
            "apiKey": "${{ secrets.ACTIONS_API_KEY }}"
          }'

      - name Project to Vercel and Capture URL
        id: deploy_step
        run: |
          # The: 5. Report Failure to API
        if: failure()
        run: |
          curl --fail -v -X PATCH '${{ secrets.API_URL }}/api/projects/${{ secrets.PROJECT_ID }}/deployments/${{ github.event.inputs.deployment_id }}' \
          -H "Content '--yes' flag is added to auto-confirm the production deployment.
          DEPLOYMENT_URL=$(vercel --prod --yes-Type: application/json" \
          --data-raw '{
            "status": "failure",
            "apiKey": "${{ secrets.ACTIONS_API_KEY }}"
          }'
