name: MERN Platform Deployment Trigger

on:
  workflow_dispatch:
    inputs:
      target_cloud:
        required: true
      deployment_id:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4

      # ===================================================================
      #  NEW DEBUGGING STEP - THIS WILL SHOW US THE REAL VALUES
      # ===================================================================
      - name: "Debug Secrets (Temporary)"
        run: |
          echo "--- Start of Secrets ---"
          echo "API_URL: [${{ secrets.API_URL }}]"
          echo "PROJECT_ID: [${{ secrets.PROJECT_ID }}]"
          echo "ACTIONS_API_KEY: [${{ secrets.ACTIONS_API_KEY }}]"
          echo "--- End of Secrets ---"

      - name: 2. Simulate Deployment & Generate URL
        id: deploy_step 
        run: |
          echo "Simulating deployment..."
          sleep 1
          echo "DEPLOYMENT_URL=https://my-app-${{ github.run_id }}.example.com" >> $GITHUB_OUTPUT
          echo "Deployment simulation finished!"

      - name: 3. Report Success to API
        if: success()
        run: |
          curl --fail -v -X PATCH "${{ secrets.API_URL }}/api/projects/${{ secrets.PROJECT_ID }}/deployments/${{ github.event.inputs.deployment_id }}" \
          -H "Content-Type: application/json" \
          --data-raw '{
            "status": "success",
            "deploymentUrl": "${{ steps.deploy_step.outputs.DEPLOYMENT_URL }}",
            "apiKey": "${{ secrets.ACTIONS_API_KEY }}"
          }'

      - name: 4. Report Failure to API
        if: failure()
        run: |
          curl --fail -v -X PATCH "${{ secrets.API_URL }}/api/projects/${{ secrets.PROJECT_ID }}/deployments/${{ github.event.inputs.deployment_id }}" \
          -H "Content-Type: application/json" \
          --data-raw '{
            "status": "failure",
            "apiKey": "${{ secrets.ACTIONS_API_KEY }}"
          }'
