name: Deploy ChatKaro via MERN Platform

on:
  workflow_dispatch:
    inputs:
      target_cloud:
        required: true
      deployment_id:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        # IMPORTANT: REPLACE 'Chat' WITH THE ACTUAL NAME OF THE FOLDER
        # INSIDE YOUR REPOSITORY THAT CONTAINS 'package.json'.
        working-directory: ./Chat

    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4

      - name: 2. Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 3. Install Dependencies
        run: npm install

      - name: 4. Build Project
        run: npm run build

      - name: 5. Install Vercel CLI
        run: npm install --global vercel
        working-directory: ${{ github.workspace }}

      - name: 6. Deploy to Vercel
        id: deploy_step
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          # The 'vercel deploy' command points to the build output folder.
          # IMPORTANT: If your project's build output is named 'build', change './dist' to './build'.
          DEPLOYMENT_URL=$(vercel deploy ./dist --prod --yes --token=${{ secrets.VERCEL_TOKEN }})
          echo "DEPLOYMENT_URL=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
      
      - name: 7. Report Success to API
        if: success()
        working-directory: ${{ github.workspace }}
        run: |
          curl --fail -v -X PATCH '${{ secrets.API_URL }}/api/projects/${{ secrets.PROJECT_ID }}/deployments/${{ github.event.inputs.deployment_id }}' \
          -H "Content-Type: application/json" \
          --data-raw '{
            "status": "success",
            "deploymentUrl": "${{ steps.deploy_step.outputs.DEPLOYMENT_URL }}",
            "apiKey": "${{ secrets.ACTIONS_API_KEY }}"
          }'

      - name: 8. Report Failure to API
        if: failure()
        working-directory: ${{ github.workspace }}
        run: |
          curl --fail -v -X PATCH '${{ secrets.API_URL }}/api/projects/${{ secrets.PROJECT_ID }}/deployments/${{ github.event.inputs.deployment_id }}' \
          -H "Content-Type: application/json" \
          --data-raw '{
            "status": "failure",
            "apiKey": "${{ secrets.ACTIONS_API_KEY }}"
          }'
