name: MERN Platform Deployment Trigger

on:
  workflow_dispatch:
    inputs:
      target_cloud:
        required: true
      deployment_id:
        required: true Your `deploy.yml`

This is the final change you will need to make to your `deploy.yml` file

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
.

1.  Go to the GitHub repository you are deploying (e.g., `ChatKaro`).
2.      - name: 1. Checkout repository code
        uses: actions/checkout@v4

      - name: 2. Install Vercel CLI
        run: npm install --global vercel

      - name: 3. Deploy  Edit the `.github/workflows/deploy.yml` file.
3.  Find the "Deploy Project to Project to Vercel and Capture URL
        id: deploy_step
        run: |
          # = Vercel" step.
4.  Modify the `vercel` command to include the `--yes` flag.

==================================================================
          #  THE FIX IS HERE: Add the '--yes' flag to the vercel command
          **Change this line:**
```yaml
DEPLOYMENT_URL=$(vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }})
