name: Deploy ChatKaro via MERN Platform

on:
  workflow_dispatch:
    inputs:
      target_cloud:
        required: true
      deployment_id:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # We have REMOVED the 'defaults' section to avoid path conflicts.

    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4

      - name: 2. Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # ===================================================================
      #  THE FIX IS HERE: We now specify the 'working-directory' for each
      #  command that needs to run inside your project's subfolder.
      # ===================================================================
      - name: 3. Install Dependencies
        run: npm install
        working-directory: ./Chat # Run 'npm install' inside the 'Chat' folder

      - name: 4. Build Project
        run: npm run build
        working-directory: ./Chat # Run 'npm run build' inside the 'Chat' folder

      - name: 5. Install Vercel CLI
        run: npm install --global vercel
        # No working-directory needed here, as it's a global install.

      - name: 6. Deploy to Vercel
        id: deploy_step
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          # We run this command from the root of the repository.
          # Vercel will now correctly use the "Root Directory: Chat" setting
          # from your project settings without any conflict.
          DEPLOYMENT_URL=$(vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }})
          echo "DEPLOYMENT_URL=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
      
      - name: 7. Report Success to API
        if: success()
        run: |
          curl --fail -v -X PATCH '${{ secrets.API_URL }}/api/projects/${{ secrets.PROJECT_ID }}/deployments/${{ github.event.inputs.deployment_id }}' \
          -H "Content-Type: application/json" \
          --data-raw '{
            "status": "success",
            "deploymentUrl": "${{ steps.deploy_step.outputs.DEPLOYMENT_URL }}",
            "apiKey": "${{ secrets.ACTIONS_API_KEY }}"
          }'

      - name: 8. Report Failure to API
        if: failure()
        run: |
          curl --fail -v -X PATCH '${{ secrets.API_URL }}/api/projects/${{ secrets.PROJECT_ID }}/deployments/${{ github.event.inputs.deployment_id }}' \
          -H "Content-Type: application/json" \
          --data-raw '{
            "status": "failure",
            "apiKey": "${{ secrets.ACTIONS_API_KEY }}"
          }'
